@startuml
left to right direction
actor User

rectangle "Colors Web App" {
  usecase "Login" as UC1
  usecase "Add Color" as UC2
  usecase "Search Colors" as UC3
}

User --> UC1
User --> UC2
User --> UC3
UC2 ..> UC1 : <<include>>
UC3 ..> UC1 : <<include>>
@enduml
